create sequence hibernate_sequence start with 1 increment by  1;
create table t_artists (id number(19,0) not null, bio varchar2(3000 char), created_date timestamp not null, name varchar2(100 char) not null, primary key (id));
create table t_customers (id number(19,0) not null, created_date timestamp not null, e_mail varchar2(255 char) not null, first_name varchar2(50 char) not null, last_name varchar2(50 char) not null, primary key (id));
create table t_items (DTYPE varchar2(31 char) not null, id number(19,0) not null, created_date timestamp not null, description varchar2(3000 char), price number(19,2) not null, title varchar2(100 char) not null, genre varchar2(100 char), music_company varchar2(255 char), isbn varchar2(15 char), language varchar2(20 char), nb_of_pages number(10,0), publication_date date, artist_fk number(19,0), publisher_fk number(19,0), primary key (id));
create table t_publishers (id number(19,0) not null, created_date timestamp not null, name varchar2(50 char) not null, primary key (id));
create table t_purchase_order_lines (id number(19,0) not null, created_date timestamp not null, quantity number(10,0) not null, item_fk number(19,0), purchase_order_fk number(19,0), primary key (id));
create table t_purchase_orders (id number(19,0) not null, created_date timestamp not null, purchase_order_date date not null, customer_fk number(19,0), primary key (id));
create table t_tracks (id number(19,0) not null, created_date timestamp not null, duration number(19,0) not null, title varchar2(255 char) not null, cd_fk number(19,0), primary key (id));
alter table t_items add constraint FKr3152tukbog585dik5qwonldg foreign key (artist_fk) references t_artists;
alter table t_items add constraint FKi6lqpcqfnc4dtsp9w473p5kkj foreign key (publisher_fk) references t_publishers;
alter table t_purchase_order_lines add constraint FKf51l5n972qc282ubbv97c1kfa foreign key (item_fk) references t_items;
alter table t_purchase_order_lines add constraint FKbjsagtstxdmdm55cxqvbxkaji foreign key (purchase_order_fk) references t_purchase_orders;
alter table t_purchase_orders add constraint FK93wd2w995ng3vyj51y4fur1hg foreign key (customer_fk) references t_customers;
alter table t_tracks add constraint FK23u6r10m0dkp0m8t5hr40ilux foreign key (cd_fk) references t_items;
INSERT INTO t_artists (id, name, bio, created_date) VALUES (1, 'Mario Vargas Llosa', 'Escritor Peruano', CURRENT_TIMESTAMP);
