create view VW_CONSULTA_ENTIDAD_PRODUCTO as
SELECT pf.PRODUCTOFINANCIEROID,
       pf.TIPOPRODUCTOID,
       ef.TIPOINSTITUCIONID,
       ef.NOMBRECOMERCIAL              AS PRODUCTO,
       ef.PATHIMAGEN,
       pa.PARAMETROID                  AS MONEDAID,
       pa.VALOR2                       AS MONEDA,
       pf.PORCENTAJETEA,
       dpf.DETALLEPRODUCTOFINANCIEROID AS CONSULTAENTIDADPRODUCTOID,
       dpf.MONTOMINIMODEPOSITO,
       dpf.MONTOMAXIMODEPOSITO,
       dpf.MONTOMINIMOPRESTAMO,
       dpf.MONTOMAXIMOPRESTAMO,
       dpf.INGRESOPERMITIDO,
       pf.PORCENTAJECOMISION,
       pf.PORCENTAJESEGURO,
       pf.PLAZOMINIMODIA,
       pf.PLAZOMAXIMODIA,
       pf.PLAZOMINIMOMES,
       pf.PLAZOMAXIMOMES,
       pf.NOMBRE,
       pf.DESCRIPCION,
       pf.OBSERVACION,
       de.DEPARTAMENTOID,
       de.NOMBRE                       AS UBICACION

FROM PRODUCTOFINANCIERO pf
         JOIN ENTIDADFINANCIERA ef ON ef.ENTIDADFINANCIERAID = pf.ENTIDADFINANCIERAID
         JOIN DETALLEPRODUCTOFINANCIERO dpf ON dpf.PRODUCTOFINANCIEROID = pf.PRODUCTOFINANCIEROID
         JOIN PARAMETRO pa ON pa.PARAMETROID = dpf.TIPOMONEDAID
         JOIN DEPARTAMENTO de ON de.DEPARTAMENTOID = ef.DEPARTAMENTOID
/

